language: node_js
node_js:
  - 'node'
  - '10'
  - 'lts/*'

matrix:
  allow_failures:
    - node_js: 'node'

services:
  - docker
cache: yarn

env:
  - NPM_TAG=`if [[ $TRAVIS_TAG =~ alpha|beta|rc ]]; then echo "next"; else echo "latest"; fi`

before_install:
  - docker run -d --rm -p 8554:8554 steabert/gst-rtsp-launch
script:
  - yarn test
  - yarn build
  - node rtsp-ws-server/tcp-ws-proxy.js >& tcp-ws-proxy.log &
  - yarn http-server examples/browser >& http-server.log &
  - yarn cypress run
deploy:
  - provider: releases
    file: dist/media-stream-library.min.js
    api_key:
      secure: MGxt16mMu4Lf+aTVbGC1laBH84u5xv8xZ24iPhrYVKbYeEyuFxV/MWI3KSFkR99dulgCJ8/IMaB3HFmWMiCg1+ngl/0i8LSq05WrlKmto0hEJvbnaxJ63a9F25L2/+VRmqXVFf6qHHu1dG15xRWFFEvJTQ+c4MKaq/zacrbRBdtcuWCnRPwfzLxJXc57eM7XV3FgQECPdABuHugmF/m26L/t55+WbQdrPYAU9jBgZeJwNs2Fdxouhhl9VV4Po/fAxdzprXGLJe8zdz7WWWIdhiF7j9xQUhueBhaXDKLnPNEIBNIJXPnc6QwPwn0MnWWwgvCdQf0d5lmLWS156RW1JrWk0/XA9l+HmUPQ4BV7s2xHHaN3Vloz1Ya9WD3IofOC+lR1HFcwc8Zkz4O8EzaojFTRmvgwkM0vXudDb/CfQmVNUqNa69RC4GTo2RykA8tjUrVFnHxL4mqp299B7K0ALKs37VyuyyO8Vm1AHrp7VKfg37yQccUF2ZZUfsMdY70HwhMLehm34HrFXFspWbeO8fMMFjAAu0GLkt6FHWfn87/yJs1NfzIB5BsQutpGwh8wu/zFqT9wNjbQV7SBQwTXv/w68zTTxmlX8lTS658Bkl3x5+qFoZ17T9l9/ZGe9/AusUp948FmCLZLXBu/FFanhXxCXfRbz0lq+ocwrwmoMwE=
    skip_cleanup: true
    on:
      tags: true
      repo: AxisCommunications/media-stream-library-js
      node: '10'
  - provider: npm
    email: stevenv@axis.com
    tag: $NPM_TAG
    api_key:
      secure: hOVjwErZg54I/Nz1HjporMgHo0cdiF0ZUW09+e0iEvoGu2geq/zTubGWDhrlpd6fJa+uUka8Cknnm8dTt+p4Dl5bDgYZISWWenpHBVo6Kxa+Z+0kE45DIEs5wUSQzo1hzsYLksBsBQJs8oaRxSvNDhBxDFIZtUhuKqL4qd26AvX9Zsj2sJC2190a50mxf+xLXkIZ1Db8fd7Wg8cHy34JDfoT1UCvuz0j93wgdnRH9tZl5c80k5+qWy1UFz5VTrvb8X8bzlVhI3tKHB1dIoBl616fff/CVJXB68hC5aQEL/At1we9NJinq2w2YukHRacmSCQOqfJlo19wEiW3iccRqaAJ21L1T7taSCRKBPVCEJPZoYDuREg35eDg4jPZskr/zo2KreQDlKeblegsijx3Pu35fTsDnjOVjRanhcvhylldMr2+AAz86JRViRJwmwFEIdD+MSWQJH3W/tGJG2Q9ea8L1aGMqwZHaGrk3MpGPXJhM8HbZLyOwGTx8oaHcO7veHaqKzMokTBNE96oHfmS8uQI1oUDkRGahgFVYTRtYD7Dcpc/D0SgcnA6SmvlkcnUpkVwkPHWTWYCi7N+rlm9/RXB3oqGoXyYiHQPu3yqhOVxgHtLn9JzSdVrlaQ3lwJE9LAWL2/wUgLHKx6RWN4TZrYSvklbAE42gTJVF8Yi3OQ=
    skip_cleanup: true
    on:
      tags: true
      repo: AxisCommunications/media-stream-library-js
      node: '10'
