# Build docker images
name: Docker

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build container image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/gst-rtsp-launch
          tag_with_sha: true
          tag_with_ref: true
          path: gst-rtsp-launch
