name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    
    services:
      rtsp:
        image: steabert/gst-rtsp-launch
        ports:
        - 8554:8554

    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Test basic video functionality
      run: |
        yarn lint
        yarn test
        yarn build
        node rtsp-ws-server/tcp-ws-proxy.js >& tcp-ws-proxy.log &
        yarn http-server examples/browser >& http-server.log &
        yarn cypress run
